// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu():Promise<void>;

export function ExampleApp():Promise<{[key: string]: string}>;

export function Greet(arg1:string):Promise<string>;

export function StartUbuntuContainer():Promise<{[key: string]: string}>;
